name: "CI"
on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: Denocord/deno-action@master
              with:
                args: '["fmt", "lib", "rest.ts", "mod.ts", "util.ts", "ws.ts", "--check"]'